// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `thrift_service_monitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____src_thrift_service_monitor_h__
#define ____src_thrift_service_monitor_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace inv
{

class ThriftServiceMonitor;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::inv::ThriftServiceMonitor>&);
::IceProxy::Ice::Object* upCast(::IceProxy::inv::ThriftServiceMonitor*);

}

}

namespace inv
{

class ThriftServiceMonitor;
bool operator==(const ThriftServiceMonitor&, const ThriftServiceMonitor&);
bool operator<(const ThriftServiceMonitor&, const ThriftServiceMonitor&);
::Ice::Object* upCast(::inv::ThriftServiceMonitor*);
typedef ::IceInternal::Handle< ::inv::ThriftServiceMonitor> ThriftServiceMonitorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::inv::ThriftServiceMonitor> ThriftServiceMonitorPrx;
void __patch(ThriftServiceMonitorPtr&, const ::Ice::ObjectPtr&);

}

namespace inv
{

struct MoniData
{
    ::Ice::Int callCnt;
    ::Ice::Int excptCnt;
    ::Ice::Long sumTimeUS;
    ::Ice::Long minTimeUS;
    ::Ice::Long maxTimeUS;

    bool operator==(const MoniData& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(callCnt != __rhs.callCnt)
        {
            return false;
        }
        if(excptCnt != __rhs.excptCnt)
        {
            return false;
        }
        if(sumTimeUS != __rhs.sumTimeUS)
        {
            return false;
        }
        if(minTimeUS != __rhs.minTimeUS)
        {
            return false;
        }
        if(maxTimeUS != __rhs.maxTimeUS)
        {
            return false;
        }
        return true;
    }

    bool operator<(const MoniData& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(callCnt < __rhs.callCnt)
        {
            return true;
        }
        else if(__rhs.callCnt < callCnt)
        {
            return false;
        }
        if(excptCnt < __rhs.excptCnt)
        {
            return true;
        }
        else if(__rhs.excptCnt < excptCnt)
        {
            return false;
        }
        if(sumTimeUS < __rhs.sumTimeUS)
        {
            return true;
        }
        else if(__rhs.sumTimeUS < sumTimeUS)
        {
            return false;
        }
        if(minTimeUS < __rhs.minTimeUS)
        {
            return true;
        }
        else if(__rhs.minTimeUS < minTimeUS)
        {
            return false;
        }
        if(maxTimeUS < __rhs.maxTimeUS)
        {
            return true;
        }
        else if(__rhs.maxTimeUS < maxTimeUS)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const MoniData& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const MoniData& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const MoniData& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const MoniData& __rhs) const
    {
        return !operator<(__rhs);
    }
};

typedef ::std::map< ::std::string, ::inv::MoniData> MoniMap;

}

namespace Ice
{
template<>
struct StreamableTraits< ::inv::MoniData>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 32;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::inv::MoniData, S>
{
    static void write(S* __os, const ::inv::MoniData& v)
    {
        __os->write(v.callCnt);
        __os->write(v.excptCnt);
        __os->write(v.sumTimeUS);
        __os->write(v.minTimeUS);
        __os->write(v.maxTimeUS);
    }
};

template<class S>
struct StreamReader< ::inv::MoniData, S>
{
    static void read(S* __is, ::inv::MoniData& v)
    {
        __is->read(v.callCnt);
        __is->read(v.excptCnt);
        __is->read(v.sumTimeUS);
        __is->read(v.minTimeUS);
        __is->read(v.maxTimeUS);
    }
};

}

namespace inv
{

class Callback_ThriftServiceMonitor_reportMoniData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ThriftServiceMonitor_reportMoniData_Base> Callback_ThriftServiceMonitor_reportMoniDataPtr;

}

namespace IceProxy
{

namespace inv
{

class ThriftServiceMonitor : virtual public ::IceProxy::Ice::Object
{
public:

    void reportMoniData(const ::inv::MoniMap& m)
    {
        reportMoniData(m, 0);
    }
    void reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx)
    {
        reportMoniData(m, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_reportMoniData(const ::inv::MoniMap& m, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_reportMoniData(m, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_reportMoniData(const ::inv::MoniMap& m, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_reportMoniData(m, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_reportMoniData(m, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_reportMoniData(m, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m)
    {
        return begin_reportMoniData(m, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx)
    {
        return begin_reportMoniData(m, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_reportMoniData(m, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_reportMoniData(m, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m, const ::inv::Callback_ThriftServiceMonitor_reportMoniDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_reportMoniData(m, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap& m, const ::Ice::Context& __ctx, const ::inv::Callback_ThriftServiceMonitor_reportMoniDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_reportMoniData(m, &__ctx, __del, __cookie);
    }

    void end_reportMoniData(const ::Ice::AsyncResultPtr&);
    
private:

    void reportMoniData(const ::inv::MoniMap&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_reportMoniData(const ::inv::MoniMap&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_secure(bool __secure) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_twoway() const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_oneway() const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_batchOneway() const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_datagram() const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_batchDatagram() const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_compress(bool __compress) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ThriftServiceMonitor> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ThriftServiceMonitor*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace inv
{

class ThriftServiceMonitor : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void reportMoniData(const ::inv::MoniMap&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace inv
{

class ThriftServiceMonitor : virtual public ::IceDelegate::inv::ThriftServiceMonitor,
                             virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void reportMoniData(const ::inv::MoniMap&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace inv
{

class ThriftServiceMonitor : virtual public ::IceDelegate::inv::ThriftServiceMonitor,
                             virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void reportMoniData(const ::inv::MoniMap&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace inv
{

class ThriftServiceMonitor : virtual public ::Ice::Object
{
public:

    typedef ThriftServiceMonitorPrx ProxyType;
    typedef ThriftServiceMonitorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void reportMoniData(const ::inv::MoniMap&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___reportMoniData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const ThriftServiceMonitor& l, const ThriftServiceMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ThriftServiceMonitor& l, const ThriftServiceMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace inv
{

template<class T>
class CallbackNC_ThriftServiceMonitor_reportMoniData : public Callback_ThriftServiceMonitor_reportMoniData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ThriftServiceMonitor_reportMoniData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ThriftServiceMonitor_reportMoniData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ThriftServiceMonitor_reportMoniData<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ThriftServiceMonitor_reportMoniData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ThriftServiceMonitor_reportMoniData<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ThriftServiceMonitor_reportMoniData : public Callback_ThriftServiceMonitor_reportMoniData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ThriftServiceMonitor_reportMoniData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ThriftServiceMonitor_reportMoniData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ThriftServiceMonitor_reportMoniData<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ThriftServiceMonitor_reportMoniData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ThriftServiceMonitor_reportMoniDataPtr
newCallback_ThriftServiceMonitor_reportMoniData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ThriftServiceMonitor_reportMoniData<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
