/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ab_dyeing_constants.h"

namespace inveno {

const ab_dyeingConstants g_ab_dyeing_constants;

ab_dyeingConstants::ab_dyeingConstants() {
}

} // namespace

