/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ab_dyeing_CONSTANTS_H
#define ab_dyeing_CONSTANTS_H

#include "ab_dyeing_types.h"

namespace inveno {

class ab_dyeingConstants {
 public:
  ab_dyeingConstants();

};

extern const ab_dyeingConstants g_ab_dyeing_constants;

} // namespace

#endif
